### PR TITLE
Added separation of choropleth layers

### PR DESCRIPTION
**Pull request by henhuy**
Added separation of choropleths (right now, simple text between layers)
Do you already have an idea/design how to separate?

### CODE REVIEW

**Comment by bmlancien** [comment]
Just by adding a line between choropleth layers and other layers.

Frame 4

**Comment by bmlancien** [comment]
Hey @nesnoj 
I thought we wouldn't have to add the value for each color on a choropleth spectrum, that's why I thought that displaying them horizontally (mockup above) would be enough. But apparently it is not necessarily the case. We might need to display each value for each color. In that case the horizontal approach doesn't make sense. Better would be to do it like in the Stemp-Tool on the map for the legend

Bildschirmfoto vom 2021-10-06 14-08-48

and simply show two colors in a square on the left panel to show that is is a choropleth and not just an area:

Bildschirmfoto vom 2021-10-06 14-13-13

What do you think?

**Comment by nesnoj** [comment]
Yes, we definitely need actual numbers, I'd really like a legend similar to the one in the StEmp-Tool, if that's possible :).
Also, I like your idea of the choropleth indication in the left panel :+1: .

**Comment by bmlancien** [comment]
@henhuy I added classes for the legend colors: 
- `name__visual--choropleth` for choropleth layers --> 2 colors: first using `background-color`, second using `border-right-color`
- `name__visual--one-color` --> 1 color using `background-color`
- `name__visual--icon` --> 1 icon using `background-image` (in case we want to use icons)

Is this something you could use or do you need to make it different?

**Comment by henhuy** [comment]
Thx for your work!
I adapted your styling code to visualize layers depending on their type.
As colors and symbols have to be loaded dynamically in backend, I moved your `name__visual` sass parts to python (see forms.py line 16) and removed it from sass file.
Looks very nice now! 
Can you check a last time, if this works for you too, @bmlancien ?

**Review by bmlancien — APPROVED** [review]
It looks good, thanks for implementing this in python!

From my side, we can merge now...

**Comment by nesnoj** [comment]
Could you please deploy this feature (and other pending features, if any) on the server, please?
I thinks it's time for me to set it up locally.. :)

**Pull request closed without merging**
